
//this for the open card page - when the user want to open a new card 
export const CARD_OPENING_START = 'CARD_OPENING_START';
export const CARD_OPENING_SUCCESS = 'CARD_OPENING_SUCCESS'; 
export const CARD_OPENING_FAIL = 'CARD_OPENING_FAIL'; 
export const PURCHASE_INIT = 'PURCHASE_INIT'; // this will be dispatched whenever we load the open card page **

export const CARD_UPDATE_START = 'CARD_UPDATE_START';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS'; 
export const CARD_UPDATE_FAIL = 'CARD_UPDATE_FAIL'; 

export const CARD_DELETE_START = 'CARD_DELETE_START'; 
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS'; 
export const CARD_DELETE_FAIL = 'CARD_DELETE_FAIL'; 


export const FETCH_CARDS_START = 'FETCH_CARDS_START'; 
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'; 
export const FETCH_CARDS_FAIL = 'FETCH_CARDS_FAIL'; 


export const WORK_OR_PARTS_ADD_START = 'WORK_OR_PARTS_ADD_START'; 
export const WORK_OR_PARTS_ADD_SUCCESS = 'WORK_OR_PARTS_ADD_SUCCESS'; 
export const WORK_OR_PARTS_ADD_FAIL = 'WORK_OR_PARTS_ADD_FAIL'; 

export const WORK_OR_PARTS_UPDATE_START = 'WORK_OR_PARTS_UPDATE_START'; 
export const WORK_OR_PARTS_UPDATE_SUCCESS = 'WORK_OR_PARTS_UPDATE_SUCCESS'; 
export const WORK_OR_PARTS_UPDATE_FAIL = 'WORK_OR_PARTS_UPDATE_FAIL'; 


export const WORK_OR_PARTS_DELETE_START = 'WORK_OR_PARTS_DELETE_START'; 
export const WORK_OR_PARTS_DELETE_SUCCESS = 'WORK_OR_PARTS_DELETE_SUCCESS'; 
export const WORK_OR_PARTS_DELETE_FAIL = 'WORK_OR_PARTS_DELETE_FAIL'; 


export const GET_ALL_CARD_DATA_START = 'GET_ALL_CARD_DATA_START'; 
export const GET_ALL_CARD_DATA_SUCCESS = 'GET_ALL_CARD_DATA_SUCCESS'; 
export const GET_ALL_CARD_DATA_FAIL = 'GET_ALL_CARD_DATA_FAIL';


export const TOAST_MODAL_CLOSE = 'TOAST_MODAL_CLOSE';



export const AUTH_SIGN_IN_START = 'AUTH_SIGN_IN_START';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL';

export const AUTH_SIGN_UP_SUCCESS= 'AUTH_SIGN_UP_SUCCESS';
export const AUTH_SIGN_UP_START= 'AUTH_SIGN_UP_START';
export const AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const PURCHASE_WORKS_INIT = 'PURCHASE_WORKS_INIT';
export const WORKS_MODAL_CLOSE = 'WORKS_MODAL_CLOSE';


export const PURCHASE_PARTS_INIT = 'PURCHASE_PARTS_INIT';
export const PARTS_MODAL_CLOSE = 'PARTS_MODAL_CLOSE';


//this for the open card page - when the user want to open a new card 
export const TASK_OPENING_START = 'TASK_OPENING_START';
export const TASK_OPENING_SUCCESS = 'TASK_OPENING_SUCCESS'; 
export const TASK_OPENING_FAIL = 'TASK_OPENING_FAIL'; 
export const TASK_INIT = 'TASK_INIT'; // this will be dispatched whenever we load the open card page **

export const FETCH_TASKS_START = 'FETCH_TASKS_START'; 
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'; 
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'; 

export const TASK_UPDATE_START = 'TASK_UPDATE_START'; 
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'; 
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'; 

export const TASK_DELETE_START = 'TASK_DELETE_START'; 
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'; 
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'; 



