
//this for the open card page - when the user want to open a new card 
export const CARD_OPENING_START = 'CARD_OPENING_START';
export const CARD_OPENING_SUCCESS = 'CARD_OPENING_SUCCESS'; 
export const CARD_OPENING_FAIL = 'CARD_OPENING_FAIL'; 
export const PURCHASE_INIT = 'PURCHASE_INIT'; // this will be dispatched whenever we load the open card page **

export const CARD_UPDATE_START = 'CARD_UPDATE_START';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS'; 
export const CARD_UPDATE_FAIL = 'CARD_UPDATE_FAIL'; 

export const CARD_DELETE_START = 'CARD_DELETE_START'; 
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS'; 
export const CARD_DELETE_FAIL = 'CARD_DELETE_FAIL'; 



export const CHANGE_VEHICLE_NUMBER_START = "CHANGE_VEHICLE_NUMBER_START";
export const CHANGE_VEHICLE_NUMBER_SUCCESS = "CHANGE_VEHICLE_NUMBER_SUCCESS";
export const CHANGE_VEHICLE_NUMBER_FAIL = "CHANGE_VEHICLE_NUMBER_FAIL";




export const MARK_CARD_IS_OPEN_START = "MARK_CARD_IS_OPEN_START";
export const MARK_CARD_IS_OPEN_SUCCESS = "MARK_CARD_IS_OPEN_SUCCESS";
export const MARK_CARD_IS_OPEN_FAIL = "MARK_CARD_IS_OPEN_FAIL";



export const MARK_CARD_IS_CLOSED_START = "MARK_CARD_IS_CLOSED_START";
export const MARK_CARD_IS_CLOSED_SUCCESS = "MARK_CARD_IS_CLOSED_SUCCESS";
export const MARK_CARD_IS_CLOSED_FAIL = "MARK_CARD_IS_CLOSED_FAIL";




export const IMAGE_OR_DOC_UPLOADING_START = "IMAGE_OR_DOC_UPLOADING_START";
export const IMAGE_OR_DOC_UPLOADING_SUCCESS = "IMAGE_OR_DOC_UPLOADING_SUCCESS";
export const IMAGE_OR_DOC_UPLOADING_FAIL = "IMAGE_OR_DOC_UPLOADING_FAIL";
export const IMAGE_OR_DOC_UPLOADING_PROGRESS = "IMAGE_OR_DOC_UPLOADING_PROGRESS";
export const ALL_UPLOAD_IS_SUCCESS = "ALL_UPLOAD_IS_SUCCESS";




export const GET_IMAGES_START = "GET_IMAGES_START";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL";


export const DELETE_IMAGES_START = "DELETE_IMAGES_START";
export const DELETE_IMAGES_SUCCESS = "DELETE_IMAGES_SUCCESS";
export const DELETE_IMAGES_FAIL = "DELETE_IMAGES_FAIL";

export const GET_DOCS_START = "GET_DOCS_START";
export const GET_DOCS_SUCCESS = "GET_DOCS_SUCCESS";
export const GET_DOCS_FAIL = "GET_DOCS_FAIL";

export const DELETE_DOCS_START = "DELETE_DOCS_START";
export const DELETE_DOCS_SUCCESS = "DELETE_DOCS_SUCCESS";
export const DELETE_DOCS_FAIL = "DELETE_DOCS_FAIL";

export const DOWNLOAD_DOC_START = "DOWNLOAD_DOC_START";
export const DOWNLOAD_DOC_SUCCESS = "DOWNLOAD_DOC_SUCCESS";
export const DOWNLOAD_DOC_FAIL = "DOWNLOAD_DOC_FAIL";

export const DOWNLOAD_IMAGE_START = "DOWNLOAD_IMAGE_START";
export const DOWNLOAD_IMAGE_SUCCESS = "DOWNLOAD_IMAGE_SUCCESS";
export const DOWNLOAD_IMAGE_FAIL = "DOWNLOAD_IMAGE_FAIL";

export const DELETE_IMAGES_OR_DOCS_START = "DELETE_IMAGES_OR_DOCS_START";
export const DELETE_IMAGES_OR_DOCS_SUCCESS = "DELETE_IMAGES_OR_DOCS_SUCCESS";
export const DELETE_IMAGES_OR_DOCS_FAIL = "DELETE_IMAGES_OR_DOCS_FAIL";

// export const GET_DATA = "GET_DATA";


export const FETCH_CARDS_START = 'FETCH_CARDS_START'; 
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'; 
export const FETCH_CARDS_FAIL = 'FETCH_CARDS_FAIL'; 


export const PURCHASE_SET_CURRENT_CARD_KEY = 'PURCHASE_SET_CURRENT_CARD_KEY'; 


export const WORK_OR_PARTS_ADD_START = 'WORK_OR_PARTS_ADD_START'; 
export const WORK_OR_PARTS_ADD_SUCCESS = 'WORK_OR_PARTS_ADD_SUCCESS'; 
export const WORK_OR_PARTS_ADD_FAIL = 'WORK_OR_PARTS_ADD_FAIL'; 

export const WORK_OR_PARTS_UPDATE_START = 'WORK_OR_PARTS_UPDATE_START'; 
export const WORK_OR_PARTS_UPDATE_SUCCESS = 'WORK_OR_PARTS_UPDATE_SUCCESS'; 
export const WORK_OR_PARTS_UPDATE_FAIL = 'WORK_OR_PARTS_UPDATE_FAIL'; 


export const WORK_OR_PARTS_DELETE_START = 'WORK_OR_PARTS_DELETE_START'; 
export const WORK_OR_PARTS_DELETE_SUCCESS = 'WORK_OR_PARTS_DELETE_SUCCESS'; 
export const WORK_OR_PARTS_DELETE_FAIL = 'WORK_OR_PARTS_DELETE_FAIL'; 


export const GET_ALL_CARD_DATA_START = 'GET_ALL_CARD_DATA_START'; 
export const GET_ALL_CARD_DATA_SUCCESS = 'GET_ALL_CARD_DATA_SUCCESS'; 
export const GET_ALL_CARD_DATA_FAIL = 'GET_ALL_CARD_DATA_FAIL';


export const TOAST_MODAL_CLOSE = 'TOAST_MODAL_CLOSE';


export const AUTH_SIGN_IN_START = 'AUTH_SIGN_IN_START';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL';



export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';




export const UPDATE_SETTING_USER_START = 'UPDATE_SETTING_USER_START'; 
export const UPDATE_SETTING_USER_SUCCESS = 'UPDATE_SETTING_USER_SUCCESS'; 
export const UPDATE_SETTING_USER_FAIL = 'UPDATE_SETTING_USER_FAIL'; 




export const AUTH_SIGN_UP_SUCCESS= 'AUTH_SIGN_UP_SUCCESS';
export const AUTH_SIGN_UP_START= 'AUTH_SIGN_UP_START';
export const AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USERS_START= 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS= 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

// export const DELETE_USER_MODAL_INIT = 'DELETE_USER_MODAL_INIT'; 
export const DELETE_USER_MODAL_CLOSE = 'DELETE_USER_MODAL_CLOSE'; 

export const USER_DELETE_START = 'USER_DELETE_START'; 
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'; 
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'; 


export const TASK_OPENING_FOR_USER_START = 'TASK_OPENING_FOR_USER_START'; 
export const TASK_OPENING_FOR_USER_SUCCESS = 'TASK_OPENING_FOR_USER_SUCCESS'; 
export const TASK_OPENING_FOR_USER_FAIL = 'TASK_OPENING_FOR_USER_FAIL'; 


export const PURCHASE_ADD_USER_MODAL_INIT = 'PURCHASE_ADD_USER_MODAL_INIT'; 
export const ADD_NEW_USER_MODAL_CLOSE = 'ADD_NEW_USER_MODAL_CLOSE'; 


export const ADD_NEW_TASK_FOR_USER_MODAL_INIT = 'ADD_NEW_TASK_FOR_USER_MODAL_INIT'; 
export const ADD_NEW_TASK_FOR_USER_MODAL_CLOSE = 'ADD_NEW_TASK_FOR_USER_MODAL_CLOSE'; 


export const PURCHASE_WORKS_INIT = 'PURCHASE_WORKS_INIT';
export const WORKS_MODAL_CLOSE = 'WORKS_MODAL_CLOSE';


export const PURCHASE_PARTS_INIT = 'PURCHASE_PARTS_INIT';
export const PARTS_MODAL_CLOSE = 'PARTS_MODAL_CLOSE';


//this for the open card page - when the user want to open a new card 
export const TASK_OPENING_START = 'TASK_OPENING_START';
export const TASK_OPENING_SUCCESS = 'TASK_OPENING_SUCCESS'; 
export const TASK_OPENING_FAIL = 'TASK_OPENING_FAIL'; 
export const TASK_INIT = 'TASK_INIT'; // this will be dispatched whenever we load the open card page **

export const FETCH_TASKS_START = 'FETCH_TASKS_START'; 
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'; 
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'; 

export const TASK_UPDATE_START = 'TASK_UPDATE_START'; 
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'; 
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'; 

export const TASK_DELETE_START = 'TASK_DELETE_START'; 
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'; 
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'; 

export const SETTING_OPENING = 'SETTING_OPENING'; 
export const SETTING_CLOSE = 'SETTING_CLOSE'; 

export const NOTIFICATION_OPENING_START = 'NOTIFICATION_OPENING_START';
export const NOTIFICATION_OPENING_SUCCESS = 'NOTIFICATION_OPENING_SUCCESS'; 
export const NOTIFICATION_OPENING_FAIL = 'NOTIFICATION_OPENING_FAIL'; 
export const NOTIFICATION_INIT = 'NOTIFICATION_INIT'; // this will be dispatched whenever we load the open card page **

export const FETCH_NOTIFICATION_START = 'FETCH_NOTIFICATION_START'; 
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS'; 
export const FETCH_NOTIFICATION_FAIL = 'FETCH_NOTIFICATION_FAIL'; 

export const NOTIFICATION_DELETE_START = 'NOTIFICATION_DELETE_START'; 
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'; 
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL'; 

export const NOTIFICATION_OPENING_FOR_USER_START = 'NOTIFICATION_OPENING_FOR_USER_START'; 
export const NOTIFICATION_OPENING_FOR_USER_SUCCESS = 'NOTIFICATION_OPENING_FOR_USER_SUCCESS'; 
export const NOTIFICATION_OPENING_FOR_USER_FAIL = 'NOTIFICATION_OPENING_FOR_USER_FAIL'; 

export const NOTIFICATION_OPENING = 'NOTIFICATION_OPENING'; 
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE'; 

export const NOTIFICATION_UPDATE_START = 'NOTIFICATION_UPDATE_START'; 
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS'; 
export const NOTIFICATION_UPDATE_FAIL = 'NOTIFICATION_UPDATE_FAIL'; 